ALTER TABLE "OfferCode" ADD COLUMN IF NOT EXISTS "offerType" TEXT NOT NULL DEFAULT 'FREE_ITEM';
ALTER TABLE "OfferCode" ADD COLUMN IF NOT EXISTS "discountAmount" DECIMAL(12,2);
ALTER TABLE "OfferCode" ADD COLUMN IF NOT EXISTS "notes" TEXT;
ALTER TABLE "OfferCode" ADD COLUMN IF NOT EXISTS "validFrom" TIMESTAMP(3);
ALTER TABLE "OfferCode" ADD COLUMN IF NOT EXISTS "validTo" TIMESTAMP(3);
