-- NO-OP: SaaS tenantId conversion was reverted 2026-09-09.
--
-- This migration used to create a `Tenant` table as phase 1 of the SaaS
-- conversion (docs/SaaS_Conversion_Roadmap_v2.md). The ERP is not being
-- converted to multi-tenant right now, and this migration was never
-- actually applied to the production database (see the P2022 outage this
-- reversion fixes) so it's safe to neutralize in place instead of deleting
-- the file (file deletion isn't available in this environment).
--
-- If/when the SaaS conversion resumes, do it on the `saas-conversion`
-- branch with a fresh migration instead of reviving this one.
SELECT 1;
