-- NO-OP: SaaS tenantId conversion was reverted 2026-09-09.
--
-- This migration used to add a `tenantId` column to ~100 existing tables
-- as phase 2 of the SaaS conversion (docs/SaaS_Conversion_Roadmap_v2.md).
-- It was never actually applied to the production database — the app code
-- was deployed expecting these columns before the migration ran, which
-- caused a site-wide P2022 "column does not exist" outage (login, orders,
-- customer search, rewards, policies, etc). Rather than run this migration
-- to fix that, the tenantId code was reverted instead, since multi-tenant
-- SaaS conversion is on hold for now.
--
-- Neutralized in place instead of deleted (file deletion isn't available
-- in this environment). If/when the SaaS conversion resumes, do it on the
-- `saas-conversion` branch with a fresh migration instead of reviving this
-- one.
SELECT 1;
